### ISSUE TITLE
FollowPath: the agent does not always manage to follow the path

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-steering-ai-framework#18]
Depending on the location and the shape of the path the user draws, the agent can loop over the path:

- It moves along the path to one end
- And then loops back to the other end

Also, when the path makes a sharp turn, e.g. when you have a portion with a V shape, the agent doesn't manage to follow the path.

**Comment by Razoric480** [comment]
Both of those situations are from the path following algorithm's ability to predict its position into the future.

- When it arrives at the end, if `predict_time_max` seconds in the future would put it on the path, the algorithm picks up that its position could be on the path, and so it starts looping. You can simulate that situation with a predict time that is non-zero and a P shape.
- When it finds a sharp corner, it predicts that its momentum will be enough to take it within an acceptable distance (`path_offset`) to the next segment of the path, and so takes a shortcut.

This allows for more graceful movement of an agent willing to cut corners because it's faster. Bringing `predict_time_max` to 0 creates an agent that will religiously follow the path, and eliminates both issues.

The sharp corner shortcut taking isn't a bug, but the looping on an open path is. There should be a check to make it prioritize the end point.

**Comment by NathanLovato** [comment]
Gotcha, thanks!
