### ISSUE TITLE
Body variable is not set in GSAIRigidBody2DAgent

### ISSUE THREAD

**Issue by p10tr3k** [GDQuest/godot-steering-ai-framework#43]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Body variable is not set in GSAIRigidBody2DAgent, so it crashes

**What is the expected behavior?**
Body variable should be set in _init method

**Comment by Razoric480** [comment]
That is on purpose - the actual body variable shouldn't get used - we use a weak reference instead so that dangling, freed bodies don't get used.

However, this instead highlights a different issue where the body is still used instead of the weak reference. I'll issue a fix for it and close your PR, because it affects more than just rigid body 2D agent, and will not actually be fixed by it (save preventing a crash that shouldn't be happening.)

**Comment by Razoric480** [comment]
I've issued a fix. Thanks for pointing it out!
